previewsEnabled: true
previewsExpireAfterDays: 1
services:
- type: web
  plan: standard
  previewPlan: starter
  name: robdimarco-express-backend
  env: node
  buildCommand: cd backend && yarn
  startCommand: cd backend && yarn start
  envVars:
  - key: MY_API_KEY
    value: production-api-key
    previewValue: test-api-key
  - key: DB_CONNECTION_STRING
    fromDatabase:
      name: robdimarco_postgres_db
      property: connectionString
- type: web
  name: robdimarco-render-todo
  env: static
  buildCommand: cd frontend && yarn install && yarn build
  staticPublishPath: ./frontend/build
  envVars:
  - key: REACT_APP_API_HOST
    fromService:
      type: web
      name: robdimarco-express-backend
      property: host
- type: pserv
  name: robdimarco-memcached
  env: image
  image:
    url: memcached
databases:
- name: robdimarco_postgres_db
  databaseName: test_db
  user: test_user
  plan: standard
  previewPlan: starter
